apiVersion: batch/v1
kind: Job
metadata:
  name: unified-single-container-job
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: main-task-executor
          image: your-repo/kaniko-skopeo-tools:latest # Placeholder - requires Kaniko, Skopeo, wget, tar, curl
          env:
            - name: JOB_TYPE # Added JOB_TYPE directly to main container
              value: "build_and_push" # Example value, can be "build_and_push" or "push_tar"
            - name: BUILD_CONTEXT_URL
              value: "http://example.com/context.tar.gz"
            - name: DOCKERFILE_PATH
              value: "Dockerfile" 
            - name: INTERMEDIATE_REGISTRY_URL
              value: "registry.internal:5000"
            - name: BUILD_IMAGE_NAME
              value: "temp-image"
            - name: BUILD_IMAGE_TAG
              value: "build-123"
            - name: IMAGE_TAR_URL
              value: "http://example.com/image.tar"
            - name: HARBOR_REGISTRY
              value: "harbor.example.com"
            - name: HARBOR_PROJECT
              value: "library"
            - name: HARBOR_IMAGE_NAME
              value: "final-image"
            - name: HARBOR_IMAGE_TAG
              value: "latest"
            - name: HARBOR_USERNAME
              valueFrom:
                secretKeyRef:
                  name: harbor-credentials
                  key: username
            - name: HARBOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-credentials
                  key: password
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/sh
              set -euo pipefail
              # ACTION_TYPE_FILE removed
              log_info() { echo "[INFO] $(date '+%Y-%m-%d %H:%M:%S') - $1"; }; log_error() { echo "[ERROR] $(date '+%Y-%m-%d %H:%M:%S') - $1" >&2; };
              ensure_env_vars_set() { for var_name in "$@"; do if [ -z "${!var_name}" ]; then log_error "ENV VAR ${var_name} not set."; exit 1; fi; done; };
              download_and_extract_build_context() { log_info "Downloading context from $BUILD_CONTEXT_URL."; ensure_env_vars_set BUILD_CONTEXT_URL; mkdir -p /workspace/context; if ! wget --no-check-certificate -O /workspace/context.tar.gz "$BUILD_CONTEXT_URL"; then log_error "Failed download context."; exit 1; fi; if ! tar -xzf /workspace/context.tar.gz -C /workspace/context/; then log_error "Failed extract context."; exit 1; fi; log_info "Context downloaded/extracted."; };
              run_kaniko_build() { log_info "Starting Kaniko build..."; ensure_env_vars_set INTERMEDIATE_REGISTRY_URL BUILD_IMAGE_NAME BUILD_IMAGE_TAG; local df_path="/workspace/context/${DOCKERFILE_PATH:-Dockerfile}"; /kaniko/executor --context dir:///workspace/context --dockerfile "${df_path}" --destination "${INTERMEDIATE_REGISTRY_URL}/${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG}" --skip-tls-verify-registry="${INTERMEDIATE_REGISTRY_URL}"; log_info "Kaniko build done: ${INTERMEDIATE_REGISTRY_URL}/${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG}"; };
              promote_to_harbor() { log_info "Promoting to Harbor..."; ensure_env_vars_set INTERMEDIATE_REGISTRY_URL BUILD_IMAGE_NAME BUILD_IMAGE_TAG HARBOR_REGISTRY HARBOR_PROJECT HARBOR_IMAGE_NAME HARBOR_IMAGE_TAG HARBOR_USERNAME HARBOR_PASSWORD; skopeo copy --src-tls-verify=false --dest-tls-verify=false --dest-creds="${HARBOR_USERNAME}:${HARBOR_PASSWORD}" "docker://${INTERMEDIATE_REGISTRY_URL}/${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG}" "docker://${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${HARBOR_IMAGE_NAME}:${HARBOR_IMAGE_TAG}"; log_info "Promoted to Harbor: ${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${HARBOR_IMAGE_NAME}:${HARBOR_IMAGE_TAG}"; };
              download_and_push_tarball() { log_info "Downloading/pushing tar from $IMAGE_TAR_URL."; ensure_env_vars_set IMAGE_TAR_URL HARBOR_REGISTRY HARBOR_PROJECT HARBOR_IMAGE_NAME HARBOR_IMAGE_TAG HARBOR_USERNAME HARBOR_PASSWORD; if ! curl -L -o /tmp/image.tar "$IMAGE_TAR_URL"; then log_error "Failed download tar $IMAGE_TAR_URL."; exit 1; fi; skopeo copy --dest-tls-verify=false --dest-creds="${HARBOR_USERNAME}:${HARBOR_PASSWORD}" "docker-archive:/tmp/image.tar" "docker://${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${HARBOR_IMAGE_NAME}:${HARBOR_IMAGE_TAG}"; log_info "Tar pushed to Harbor: ${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${HARBOR_IMAGE_NAME}:${HARBOR_IMAGE_TAG}"; };
              
              if [ -z "${JOB_TYPE}" ]; then log_error "JOB_TYPE env var not set."; exit 1; fi;
              log_info "Action based on JOB_TYPE: $JOB_TYPE";
              
              INTERNAL_ACTION="" # Renamed from ACTION to avoid conflict if any global 'ACTION' env var exists
              case "${JOB_TYPE}" in
                "build_and_push") INTERNAL_ACTION="build";;
                "push_tar") INTERNAL_ACTION="push_tar";;
                *) log_error "Invalid JOB_TYPE: ${JOB_TYPE}. Allowed: 'build_and_push', 'push_tar'"; exit 1;;
              esac

              case "$INTERNAL_ACTION" in
                "build") log_info "Exec 'build' path..."; download_and_extract_build_context; run_kaniko_build; promote_to_harbor; log_info "'Build' path done.";;
                "push_tar") log_info "Exec 'push_tar' path..."; download_and_push_tarball; log_info "'Push Tar' path done.";;
                *) log_error "Unknown action derived: $INTERNAL_ACTION"; exit 1;;
              esac;
              exit 0
